### ISSUE TITLE
Enhance dependency management

### ISSUE THREAD

**Issue by phomer** [tendermint/go-keys#1]
For my environment, since I only had tendermint checked out, I had to go get:

- github.com/bgentry/speakeasy
- github.com/gorilla/handlers
- github.com/gorilla/mux
- github.com/spf13/cobra
- github.com/spf13/viper
- gopkg.in/go-playground/validator.v9
- github.com/stretchr/testify/assert

Also I had to switch go-crypto to develop version.

Maybe this should be set up with glide, a vendor dir, etc?

**Comment by ethanfrey** [comment]
Yup, this should be with glide.

Do you want to try your hand on a PR for this one?  Make a branch, create the glide.{lock,yaml} files (glide init i think, then adjust them).  Add a get_vendor_deps command to the Makefile like basecoin or light-client or ....

**Comment by ethanfrey** [comment]
You should have write access to this repo, ping me if not.

**Comment by phomer** [comment]
Okay, it should be fun.

**Comment by ethanfrey** [comment]
Fixed with PR #4 from @phomer 
Merged. Thank you
