### ISSUE TITLE
Default user directory

### ISSUE THREAD

**Issue by phomer** [tendermint/go-keys#2]
To get keys running I had to create ~/.tlc.

It should probably be automatically created if it doesn't already exist.

**Comment by ethanfrey** [comment]
Nice catch.  Yeah, I do some logic in `filestorage.New()` to create a directory if it doesn't exist already.  Guess I missed it some other place. Another PR?

**Comment by ethanfrey** [comment]
Fixed in 76ace969256d2e3c2c89ddc8566489c9b8cb78bd
