### ISSUE TITLE
Root flag doesn't work sometimes.

### ISSUE THREAD

**Issue by phomer** [tendermint/go-keys#3]
$ keys list -root ~/junk
panic: mkdir oot/keys: no such file or directory

$ keys list -root .
panic: mkdir oot/keys: no such file or directory

$ keys list -r .
List Keys: readdirent: not a directory

keys list -r ~/junk does work correctly.

**Comment by ethanfrey** [comment]
This seems to be a standard usage with cobra. Also note the usage info from `keys --help`:

```
  -r, --root string       root directory for config and data (default "/Users/ethan/.tlc")
```

`keys -r ~/junk` works, as does `keys --root ~/junk`.

`keys -rfoo` = `keys -r foo` = `keys --root foo`

The only "fix" I can do it remove the shortcut, so `-r` is illegal and only `--root` is supported.  Closing for now, please re-open if you think I this flag handling is too confusing (and then bring in bucky and rigel who are working on cobra for other packages for a standard solution).
